var businessJsonsPromises = [
  "banking-n-finance.json",
  "cigarettes.json",
  "communications.json",
  "constructions.json",
  "entertainment-n-tourism.json",
  "food-n-beverages.json",
  "health-n-beauty-product.json",
  "health-services.json",
  "industrial-estates-offices.json",
  "manufacturing.json",
  "media.json",
  "port-terminals.json",
  "retail.json",
  "trading-companies.json",
  "transport.json",
].map((i) => fetch(`data/${i}`).then((response) => response.json()));